"""
PR creator: creates a branch, commits the patch, and opens a GitHub PR.
"""

import os
import subprocess
import tempfile
from github import Github


PR_BODY_TEMPLATE = """\
## 🤖 Automated fix for #{issue_number}

**Root cause:** {root_cause}

**Fix:** {fix_approach}

---

This PR was generated by [bug-fixer-agent](https://github.com/your-username/bug-fixer-agent).

Closes #{issue_number}
"""


class PRCreator:
    def __init__(self, repo_dir: str):
        self.repo_dir = repo_dir
        self.gh = Github(os.environ["GITHUB_TOKEN"])

    def create(self, issue: dict, patch: str, plan: dict) -> str:
        """
        Apply patch permanently, push branch, open PR.
        Returns the PR URL.
        """
        branch_name = plan["branch_name"]
        default_branch = issue["default_branch"]

        # Configure git identity
        self._git(["config", "user.email", "bug-fixer-agent@example.com"])
        self._git(["config", "user.name", "Bug Fixer Agent"])

        # Create a new branch
        self._git(["checkout", "-b", branch_name])

        # Apply the patch
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".patch", delete=False
        ) as f:
            f.write(patch)
            patch_file = f.name

        try:
            self._git(["apply", patch_file])
        finally:
            os.unlink(patch_file)

        # Commit
        self._git(["add", "-A"])
        commit_msg = (
            f"fix: resolve #{issue['number']} — {issue['title'][:60]}\n\n"
            f"Root cause: {plan['root_cause']}\n\n"
            f"Co-authored-by: bug-fixer-agent <bot@example.com>"
        )
        self._git(["commit", "-m", commit_msg])

        # Push
        token = os.environ["GITHUB_TOKEN"]
        repo_full_name = issue["repo_full_name"]
        remote_url = f"https://{token}@github.com/{repo_full_name}.git"
        self._git(["push", remote_url, f"HEAD:{branch_name}"])

        # Open PR via API
        repo = self.gh.get_repo(repo_full_name)
        pr = repo.create_pull(
            title=f"fix: #{issue['number']} — {issue['title'][:72]}",
            body=PR_BODY_TEMPLATE.format(
                issue_number=issue["number"],
                root_cause=plan["root_cause"],
                fix_approach=plan["fix_approach"],
            ),
            head=branch_name,
            base=default_branch,
        )
        return pr.html_url

    def _git(self, args: list[str]) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git"] + args,
            cwd=self.repo_dir,
            check=True,
            capture_output=True,
            text=True,
        )
